import "./scripts/headerController";
import "./assets/scss/index";
import "./scripts/downloadVideo";
import "./scripts/settings/settings-panel-switcher";
import "./scripts/settings/config-settings-controller";
import "./scripts/settings/video-settings-controller";
import "./scripts/data-collection/DataCollection";
import "./scripts/data-collection/data-page";
import "./scripts/playlist/playlist";
import "./scripts/home"